### ISSUE TITLE
libQt5Core.so.5 patching randomly breaks in TravisCI

### ISSUE THREAD

**Issue by ribtoks** [Ribtoks/linuxdeploy#3]
Current hypothesis is if `patchelf` is being run on libQt5Core then it breaks
(previously there was a bug related to race between `patchelf` and `pathQtCore()` function which overwrote one another, but now builds reproducibly fail)

**Comment by probonopd** [comment]
Possibly caused by https://github.com/NixOS/patchelf/issues/124

**Comment by ribtoks** [comment]
Does not repro if using [Debian's patchelf](https://anonscm.debian.org/cgit/collab-maint/patchelf.git/log/)
