### ISSUE TITLE
Is changing GPL to MIT legal?

### ISSUE THREAD

**Issue by ghost** [Ribtoks/linuxdeploy#5]
@probonopd, check and correct me, but look like this commit is illegal...

- https://github.com/ribtoks/linuxdeploy/commit/f33dd0b3b203b899e7d8d7d3be90edc4475e20f2

**Comment by ribtoks** [comment]
@Symbian9 this tool has been written from scratch, not just copy-pasting linuxdeploy-qt source code and changing C++ line to Go line. It has completely different architecture than linuxdeploy-qt.

**Comment by ghost** [comment]
> this tool has been written from scratch, not just copy-pasting linuxdeploy-qt source code

Commit information says that this is not "from scratch".

**Comment by ribtoks** [comment]
@Symbian9 It was written from scratch. Commit information says that I released it under GNU GPL, but later I decided to switch it to MIT after somebody advised me so.
